#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=============================================================================
Subagent Engine with Context-Purge — AIDD v5.1 Enterprise
=============================================================================
Ephemeral subagent orchestration for vertical-slice composition.

Each subagent receives ONLY its slice's SPEC (~1200 tokens), executes in
isolation (subprocess), writes results to disk, and is then PURGED —
zero history contamination between slices.

Classes:
  - SubagentSpec:  Holds module_name, spec_text, prompt_template
  - SubagentEngine: Spawns individual subagents via subprocess
  - ContextPurgeEngine: Manages full lifecycle (spawn -> execute -> collect -> purge)
"""

import json
import os
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class SubagentSpec:
    """Specification for a single vertical-slice subagent."""
    module_name: str
    spec_text: str  # The slice SPEC (~1200 tokens max)
    prompt_template: str = ""
    target_dir: str = "."
    extra_args: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not self.prompt_template:
            self.prompt_template = (
                "You are an AIDD vertical-slice builder. "
                "Generate the complete module '{module_name}' following the SPEC below. "
                "Write all files to disk under the target directory. "
                "Return a JSON result with keys: module_name, status, files_created, errors.\n\n"
                "## SPEC\n{spec_text}\n\n"
                "## Target Directory\n{target_dir}\n"
            )

    def render_prompt(self) -> str:
        return self.prompt_template.format(
            module_name=self.module_name,
            spec_text=self.spec_text,
            target_dir=self.target_dir,
        )


@dataclass
class SubagentResult:
    """Result returned by a completed subagent."""
    module_name: str
    status: str  # "success", "failed", "error"
    files_created: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    duration_ms: float = 0.0
    exit_code: int = -1
    stdout: str = ""
    stderr: str = ""


# ---------------------------------------------------------------------------
# Template for the subagent worker script (written to a temp .py file).
# Placeholders: __MODULE_NAME__, __TARGET_DIR__, __RESULT_PATH__
# ---------------------------------------------------------------------------
_WORKER_TEMPLATE = r'''#!/usr/bin/env python3
"""Ephemeral subagent worker — auto-generated, self-destructing."""
import json, os, sys

module_name = "__MODULE_NAME__"
target_dir  = r"__TARGET_DIR__"
result_path = r"__RESULT_PATH__"

files_created = []
errors = []

try:
    module_src = os.path.join(target_dir, "src", "modules", module_name)
    os.makedirs(module_src, exist_ok=True)

    # ---- __init__.py ----
    init_path = os.path.join(module_src, "__init__.py")
    with open(init_path, "w", encoding="utf-8") as fh:
        fh.write("# Module: " + module_name + "\n")
    files_created.append(init_path)

    # ---- models.py ----
    class_name = module_name.capitalize()
    models_path = os.path.join(module_src, "models.py")
    with open(models_path, "w", encoding="utf-8") as fh:
        fh.write(
            '"""' + "\n"
            "Models for module: " + module_name + "\n"
            "Auto-generated by AIDD Subagent Engine." + "\n"
            '"""' + "\n"
            "import datetime" + "\n"
            "import json" + "\n"
            "from dataclasses import dataclass, field, asdict" + "\n"
            "from typing import Optional, Dict, Any" + "\n"
            "\n"
            "\n"
            "@dataclass" + "\n"
            "class " + class_name + ":" + "\n"
            '    """Primary entity for ' + module_name + ' domain."""' + "\n"
            "    id: Optional[int] = None" + "\n"
            '    titulo: str = ""' + "\n"
            '    descricao: str = ""' + "\n"
            '    status: str = "ativo"' + "\n"
            "    payload_json: str = '{}'" + "\n"
            "    criado_em: str = field(default_factory=lambda: datetime.datetime.now().isoformat())" + "\n"
            "    atualizado_em: str = field(default_factory=lambda: datetime.datetime.now().isoformat())" + "\n"
            "    deletado_em: Optional[str] = None" + "\n"
            "\n"
            "    def to_dict(self) -> Dict[str, Any]:" + "\n"
            "        return asdict(self)" + "\n"
            "\n"
            "    @classmethod" + "\n"
            "    def from_row(cls, row: tuple) -> '" + class_name + "':" + "\n"
            "        if not row:" + "\n"
            "            return cls()" + "\n"
            '        cols = ["id", "titulo", "descricao", "status", "payload_json",' + "\n"
            '                "criado_em", "atualizado_em", "deletado_em"]' + "\n"
            "        return cls(**{k: v for k, v in zip(cols, row) if v is not None})" + "\n"
        )
    files_created.append(models_path)

    # ---- services.py ----
    table_name = "mod_" + module_name
    services_path = os.path.join(module_src, "services.py")
    with open(services_path, "w", encoding="utf-8") as fh:
        fh.write(
            '"""' + "\n"
            "Services for module: " + module_name + "\n"
            "Auto-generated by AIDD Subagent Engine." + "\n"
            '"""' + "\n"
            "import datetime" + "\n"
            "import json" + "\n"
            "from typing import List, Optional, Dict, Any" + "\n"
            "\n"
            'TABLE = "' + table_name + '"' + "\n"
            "\n"
            "\n"
            "def init_db(conn):" + "\n"
            '    """Create table if not exists."""' + "\n"
            '    conn.execute("""' + "\n"
            "        CREATE TABLE IF NOT EXISTS " + table_name + " (" + "\n"
            "            id INTEGER PRIMARY KEY AUTOINCREMENT," + "\n"
            "            titulo TEXT NOT NULL DEFAULT ''," + "\n"
            "            descricao TEXT DEFAULT ''," + "\n"
            "            status TEXT DEFAULT 'ativo'," + "\n"
            "            payload_json TEXT DEFAULT '{}'," + "\n"
            "            criado_em TEXT NOT NULL," + "\n"
            "            atualizado_em TEXT NOT NULL," + "\n"
            "            deletado_em TEXT" + "\n"
            "        )" + "\n"
            '    """)' + "\n"
            '    idx_status_sql = "CREATE INDEX IF NOT EXISTS idx_" + table_name + "_status ON " + table_name + "(status)"' + "\n"
            '    conn.execute(idx_status_sql)' + "\n"
            '    idx_del_sql = "CREATE INDEX IF NOT EXISTS idx_" + table_name + "_del ON " + table_name + "(deletado_em)"' + "\n"
            '    conn.execute(idx_del_sql)' + "\n"
            "    conn.commit()" + "\n"
            "\n"
            "\n"
            "def criar(conn, dados: Dict[str, Any]) -> Dict[str, Any]:" + "\n"
            "    now = datetime.datetime.now().isoformat()" + "\n"
            '    sql_insert = "INSERT INTO " + table_name + " (titulo, descricao, status, payload_json, criado_em, atualizado_em) VALUES (?,?,?,?,?,?)"' + "\n"
            "    cur = conn.execute(" + "\n"
            "        sql_insert," + "\n"
            '        (dados.get("titulo",""), dados.get("descricao",""), dados.get("status","ativo"),' + "\n"
            '         json.dumps(dados.get("payload_json",{})), now, now)' + "\n"
            "    )" + "\n"
            "    conn.commit()" + "\n"
            '    return {"id": cur.lastrowid, "criado_em": now, "status": "ativo"}' + "\n"
            "\n"
            "\n"
            "def listar(conn, filtro: str = '', limit: int = 100, offset: int = 0) -> List[Dict]:" + "\n"
            '    where = "WHERE deletado_em IS NULL"' + "\n"
            "    params = []" + "\n"
            "    if filtro:" + "\n"
            '        where += " AND (titulo LIKE ? OR descricao LIKE ?)"' + "\n"
            '        params = ["%" + filtro + "%", "%" + filtro + "%"]' + "\n"
            '    sql_select = "SELECT id, titulo, descricao, status, payload_json, criado_em, atualizado_em, deletado_em FROM " + table_name + " " + where + " ORDER BY id DESC LIMIT ? OFFSET ?"' + "\n"
            "    rows = conn.execute(" + "\n"
            "        sql_select," + "\n"
            "        params + [limit, offset]" + "\n"
            "    ).fetchall()" + "\n"
            '    cols = ["id","titulo","descricao","status","payload_json","criado_em","atualizado_em","deletado_em"]' + "\n"
            "    return [dict(zip(cols, r)) for r in rows]" + "\n"
            "\n"
            "\n"
            "def obter(conn, id: int) -> Optional[Dict]:" + "\n"
            '    sql_obter = "SELECT id, titulo, descricao, status, payload_json, criado_em, atualizado_em, deletado_em FROM " + table_name + " WHERE id=? AND deletado_em IS NULL"' + "\n"
            "    row = conn.execute(" + "\n"
            "        sql_obter," + "\n"
            "        (id,)" + "\n"
            "    ).fetchone()" + "\n"
            "    if not row:" + "\n"
            "        return None" + "\n"
            '    cols = ["id","titulo","descricao","status","payload_json","criado_em","atualizado_em","deletado_em"]' + "\n"
            "    return dict(zip(cols, row))" + "\n"
            "\n"
            "\n"
            "def atualizar(conn, id: int, dados: Dict[str, Any]) -> Dict:" + "\n"
            "    now = datetime.datetime.now().isoformat()" + "\n"
            "    fields = []" + "\n"
            "    values = []" + "\n"
            '    for k in ["titulo","descricao","status"]:' + "\n"
            "        if k in dados:" + "\n"
            '            fields.append(k + "=?")' + "\n"
            "            values.append(dados[k])" + "\n"
            '    if "payload_json" in dados:' + "\n"
            '        fields.append("payload_json=?")' + "\n"
            '        values.append(json.dumps(dados["payload_json"]))' + "\n"
            '    fields.append("atualizado_em=?")' + "\n"
            "    values.append(now)" + "\n"
            "    values.append(id)" + "\n"
            '    sql_update = "UPDATE " + table_name + " SET " + ",".join(fields) + " WHERE id=?"' + "\n"
            "    conn.execute(sql_update, values)" + "\n"
            "    conn.commit()" + "\n"
            '    return {"id": id, "atualizado_em": now}' + "\n"
            "\n"
            "\n"
            "def deletar(conn, id: int) -> Dict:" + "\n"
            "    now = datetime.datetime.now().isoformat()" + "\n"
            '    sql_delete = "UPDATE " + table_name + " SET deletado_em=? WHERE id=?"' + "\n"
            "    conn.execute(sql_delete, (now, id))" + "\n"
            "    conn.commit()" + "\n"
            '    return {"id": id, "deletado_em": now}' + "\n"
            "\n"
            "\n"
            "def metricas(conn) -> Dict[str, Any]:" + "\n"
            '    sql_total = "SELECT COUNT(*) FROM " + table_name + " WHERE deletado_em IS NULL"' + "\n"
            "    total = conn.execute(sql_total).fetchone()[0]" + "\n"
            '    sql_ativos = "SELECT COUNT(*) FROM " + table_name + " WHERE status=\'ativo\' AND deletado_em IS NULL"' + "\n"
            "    ativos = conn.execute(sql_ativos).fetchone()[0]" + "\n"
            '    return {"total": total, "ativos": ativos, "taxa_ativos": round(ativos/total*100,1) if total else 0}' + "\n"
        )
    files_created.append(services_path)

    # ---- routes.py ----
    prefix = "/api/" + module_name
    routes_path = os.path.join(module_src, "routes.py")
    with open(routes_path, "w", encoding="utf-8") as fh:
        fh.write(
            '"""' + "\n"
            "Routes for module: " + module_name + "\n"
            "Auto-generated by AIDD Subagent Engine." + "\n"
            '"""' + "\n"
            "import json" + "\n"
            "from typing import Dict, Any" + "\n"
            "\n"
            'PREFIX = "' + prefix + '"' + "\n"
            "\n"
            "\n"
            "def register_routes(app, db):" + "\n"
            '    """Register all REST routes for this module."""' + "\n"
            "    from . import services" + "\n"
            "\n"
            "    with db.get_connection() as conn:" + "\n"
            "        services.init_db(conn)" + "\n"
            "\n"
            '    @app.route(PREFIX + "/criar", methods=["POST"])' + "\n"
            "    def route_criar():" + "\n"
            '        dados = json.loads(app.request.data or "{}")' + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            result = services.criar(conn, dados)" + "\n"
            "        return json.dumps(result), 201" + "\n"
            "\n"
            '    @app.route(PREFIX + "/listar")' + "\n"
            "    def route_listar():" + "\n"
            '        filtro = app.request.args.get("q","")' + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            items = services.listar(conn, filtro=filtro)" + "\n"
            "        return json.dumps(items), 200" + "\n"
            "\n"
            '    @app.route(PREFIX + "/obter")' + "\n"
            "    def route_obter():" + "\n"
            '        id = int(app.request.args.get("id",0))' + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            item = services.obter(conn, id)" + "\n"
            "        if not item:" + "\n"
            '            return json.dumps({"erro":"Nao encontrado"}), 404' + "\n"
            "        return json.dumps(item), 200" + "\n"
            "\n"
            '    @app.route(PREFIX + "/atualizar", methods=["POST"])' + "\n"
            "    def route_atualizar():" + "\n"
            '        dados = json.loads(app.request.data or "{}")' + "\n"
            '        id = dados.pop("id",0)' + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            result = services.atualizar(conn, id, dados)" + "\n"
            "        return json.dumps(result), 200" + "\n"
            "\n"
            '    @app.route(PREFIX + "/deletar", methods=["POST"])' + "\n"
            "    def route_deletar():" + "\n"
            '        dados = json.loads(app.request.data or "{}")' + "\n"
            '        id = dados.get("id",0)' + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            result = services.deletar(conn, id)" + "\n"
            "        return json.dumps(result), 200" + "\n"
            "\n"
            '    @app.route(PREFIX + "/metricas")' + "\n"
            "    def route_metricas():" + "\n"
            "        with db.get_connection() as conn:" + "\n"
            "            m = services.metricas(conn)" + "\n"
            "        return json.dumps(m), 200" + "\n"
        )
    files_created.append(routes_path)

    # ---- mcp_tools.py ----
    mcp_path = os.path.join(module_src, "mcp_tools.py")
    with open(mcp_path, "w", encoding="utf-8") as fh:
        fh.write(
            '"""' + "\n"
            "MCP Tools for module: " + module_name + "\n"
            "Auto-generated by AIDD Subagent Engine." + "\n"
            "JSON-RPC 2.0 tool definitions for Model Context Protocol." + "\n"
            '"""' + "\n"
            "\n"
            "MCP_TOOLS = [" + "\n"
            "    {" + "\n"
            '        "name": "mod_' + module_name + '_listar",' + "\n"
            '        "description": "Lista registros do modulo ' + module_name + ' com filtro opcional",' + "\n"
            '        "inputSchema": {' + "\n"
            '            "type": "object",' + "\n"
            '            "properties": {' + "\n"
            '                "filtro": {"type": "string", "description": "Termo de busca"},' + "\n"
            '                "limit": {"type": "integer", "default": 100},' + "\n"
            '                "offset": {"type": "integer", "default": 0}' + "\n"
            "            }" + "\n"
            "        }" + "\n"
            "    }," + "\n"
            "    {" + "\n"
            '        "name": "mod_' + module_name + '_criar",' + "\n"
            '        "description": "Cria novo registro no modulo ' + module_name + '",' + "\n"
            '        "inputSchema": {' + "\n"
            '            "type": "object",' + "\n"
            '            "properties": {' + "\n"
            '                "titulo": {"type": "string"},' + "\n"
            '                "descricao": {"type": "string"},' + "\n"
            '                "status": {"type": "string", "default": "ativo"},' + "\n"
            '                "payload_json": {"type": "object"}' + "\n"
            "            }," + "\n"
            '            "required": ["titulo"]' + "\n"
            "        }" + "\n"
            "    }," + "\n"
            "    {" + "\n"
            '        "name": "mod_' + module_name + '_obter",' + "\n"
            '        "description": "Obtem registro por ID no modulo ' + module_name + '",' + "\n"
            '        "inputSchema": {' + "\n"
            '            "type": "object",' + "\n"
            '            "properties": {' + "\n"
            '                "id": {"type": "integer"}' + "\n"
            "            }," + "\n"
            '            "required": ["id"]' + "\n"
            "        }" + "\n"
            "    }," + "\n"
            "    {" + "\n"
            '        "name": "mod_' + module_name + '_atualizar",' + "\n"
            '        "description": "Atualiza registro existente no modulo ' + module_name + '",' + "\n"
            '        "inputSchema": {' + "\n"
            '            "type": "object",' + "\n"
            '            "properties": {' + "\n"
            '                "id": {"type": "integer"},' + "\n"
            '                "titulo": {"type": "string"},' + "\n"
            '                "descricao": {"type": "string"},' + "\n"
            '                "status": {"type": "string"}' + "\n"
            "            }," + "\n"
            '            "required": ["id"]' + "\n"
            "        }" + "\n"
            "    }," + "\n"
            "    {" + "\n"
            '        "name": "mod_' + module_name + '_deletar",' + "\n"
            '        "description": "Remove registro (soft-delete) no modulo ' + module_name + '",' + "\n"
            '        "inputSchema": {' + "\n"
            '            "type": "object",' + "\n"
            '            "properties": {' + "\n"
            '                "id": {"type": "integer"}' + "\n"
            "            }," + "\n"
            '            "required": ["id"]' + "\n"
            "        }" + "\n"
            "    }" + "\n"
            "]" + "\n"
        )
    files_created.append(mcp_path)

    # ---- Unit test ----
    test_dir = os.path.join(target_dir, "tests", "unit")
    os.makedirs(test_dir, exist_ok=True)
    test_path = os.path.join(test_dir, "test_" + module_name + ".py")
    with open(test_path, "w", encoding="utf-8") as fh:
        fh.write(
            '"""' + "\n"
            "Unit tests for module: " + module_name + "\n"
            "Auto-generated by AIDD Subagent Engine." + "\n"
            '"""' + "\n"
            "import os, sys, pytest" + "\n"
            "\n"
            "src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '..', 'src')" + "\n"
            "if src_dir not in sys.path:" + "\n"
            "    sys.path.insert(0, src_dir)" + "\n"
            "\n"
            "\n"
            "def test_module_import():" + "\n"
            '    """Module can be imported without errors."""' + "\n"
            "    from modules." + module_name + " import models" + "\n"
            "    assert hasattr(models, '" + class_name + "')" + "\n"
            "\n"
            "\n"
            "def test_model_creation():" + "\n"
            '    """Model dataclass can be instantiated."""' + "\n"
            "    from modules." + module_name + ".models import " + class_name + "\n"
            '    obj = ' + class_name + '(titulo="Teste")' + "\n"
            '    assert obj.titulo == "Teste"' + "\n"
            '    assert obj.status == "ativo"' + "\n"
            "    d = obj.to_dict()" + "\n"
            '    assert "titulo" in d' + "\n"
        )
    files_created.append(test_path)

except Exception as e:
    errors.append(str(e))

# Write result manifest
result = {
    "module_name": module_name,
    "status": "success" if not errors else "failed",
    "files_created": files_created,
    "errors": errors
}
with open(result_path, "w", encoding="utf-8") as fh:
    json.dump(result, fh, ensure_ascii=False, indent=2)
'''


class SubagentEngine:
    """
    Spawns individual subagents as isolated subprocesses.
    Each subagent receives only its slice's SPEC and writes files to disk.
    Results are read back from a JSON manifest on disk.
    """

    def __init__(self, python_executable: Optional[str] = None):
        self.python = python_executable or sys.executable

    def spawn(self, spec: SubagentSpec) -> SubagentResult:
        """
        Launch a subagent for one vertical slice.
        The subagent runs as a subprocess with a minimal prompt.
        After completion, its result is read from disk and the manifest is purged.
        """
        module_name = spec.module_name
        target_dir = os.path.abspath(spec.target_dir)
        result_path = os.path.join(target_dir, ".subagent_result_" + module_name + ".json")

        # Build worker script from template
        worker_code = (
            _WORKER_TEMPLATE
            .replace("__MODULE_NAME__", module_name)
            .replace("__TARGET_DIR__", target_dir)
            .replace("__RESULT_PATH__", result_path)
        )

        # Write worker to a temp file
        fd, script_path = tempfile.mkstemp(suffix=".py", prefix="aidd_subagent_")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(worker_code)

            t0 = time.time()
            try:
                proc = subprocess.run(
                    [self.python, script_path],
                    cwd=target_dir,
                    capture_output=True,
                    text=True,
                    timeout=300,
                    errors="replace",
                )
                duration_ms = (time.time() - t0) * 1000

                result = self._read_result(result_path, module_name)
                result.duration_ms = duration_ms
                result.exit_code = proc.returncode
                result.stdout = proc.stdout[-2000:] if proc.stdout else ""
                result.stderr = proc.stderr[-2000:] if proc.stderr else ""

                if proc.returncode != 0 and result.status == "success":
                    result.status = "failed"
                    if not result.errors:
                        result.errors = ["Process exited with code " + str(proc.returncode)]

                return result

            except subprocess.TimeoutExpired:
                return SubagentResult(
                    module_name=module_name,
                    status="error",
                    errors=["Subagent timed out after 300s"],
                    duration_ms=(time.time() - t0) * 1000,
                    exit_code=-1,
                )
            except Exception as e:
                return SubagentResult(
                    module_name=module_name,
                    status="error",
                    errors=[str(e)],
                    duration_ms=(time.time() - t0) * 1000,
                    exit_code=-1,
                )
            finally:
                # Purge: remove result manifest and temp script
                self._purge_artifact(result_path)
        finally:
            self._purge_artifact(script_path)

    def _read_result(self, result_path: str, module_name: str) -> SubagentResult:
        """Read the subagent result manifest from disk."""
        if not os.path.exists(result_path):
            return SubagentResult(
                module_name=module_name,
                status="error",
                errors=["Result manifest not found on disk"],
            )
        try:
            with open(result_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return SubagentResult(
                module_name=data.get("module_name", module_name),
                status=data.get("status", "error"),
                files_created=data.get("files_created", []),
                errors=data.get("errors", []),
            )
        except Exception as e:
            return SubagentResult(
                module_name=module_name,
                status="error",
                errors=["Failed to parse result manifest: " + str(e)],
            )

    @staticmethod
    def _purge_artifact(path: str):
        """Remove an artifact file (context purge)."""
        try:
            if os.path.exists(path):
                os.remove(path)
        except OSError:
            pass  # Best-effort purge


class ContextPurgeEngine:
    """
    Manages the full subagent lifecycle:
      spawn -> execute -> collect results -> purge

    Tracks active subagents and their completion status.
    Provides get_results() to collect all slice outputs.
    """

    def __init__(self, python_executable: Optional[str] = None):
        self.engine = SubagentEngine(python_executable=python_executable)
        self._results: Dict[str, SubagentResult] = {}
        self._active: Dict[str, bool] = {}
        self._order: List[str] = []

    def spawn(self, spec: SubagentSpec) -> SubagentResult:
        """
        Spawn a subagent for a vertical slice.
        Executes synchronously (blocking), then purges context.
        """
        module_name = spec.module_name
        self._active[module_name] = True
        self._order.append(module_name)

        result = self.engine.spawn(spec)
        self._results[module_name] = result
        self._active[module_name] = False

        return result

    def spawn_all(self, specs: List[SubagentSpec]) -> Dict[str, SubagentResult]:
        """
        Spawn all subagents sequentially.
        Each runs in isolation; context is purged between slices.
        """
        for spec in specs:
            self.spawn(spec)
        return self._results

    def get_results(self) -> Dict[str, SubagentResult]:
        """Return all collected results keyed by module_name."""
        return dict(self._results)

    def get_ordered_results(self) -> List[SubagentResult]:
        """Return results in spawn order."""
        return [self._results[m] for m in self._order if m in self._results]

    def get_summary(self) -> Dict[str, Any]:
        """Return a summary report of all subagent executions."""
        total = len(self._results)
        success = sum(1 for r in self._results.values() if r.status == "success")
        failed = sum(1 for r in self._results.values() if r.status == "failed")
        errors = sum(1 for r in self._results.values() if r.status == "error")
        total_files = sum(len(r.files_created) for r in self._results.values())
        total_duration = sum(r.duration_ms for r in self._results.values())

        return {
            "total_modules": total,
            "success": success,
            "failed": failed,
            "errors": errors,
            "total_files_created": total_files,
            "total_duration_ms": round(total_duration, 2),
            "status": "APROVADO" if (failed == 0 and errors == 0) else "REPROVADO",
            "modules": {
                name: {
                    "status": r.status,
                    "files_created": len(r.files_created),
                    "errors": r.errors,
                    "duration_ms": round(r.duration_ms, 2),
                }
                for name, r in self._results.items()
            },
        }

    def is_active(self) -> bool:
        """Check if any subagent is currently running."""
        return any(self._active.values())

    @property
    def active_count(self) -> int:
        """Number of currently active subagents."""
        return sum(1 for v in self._active.values() if v)

    @property
    def completed_count(self) -> int:
        """Number of completed subagents."""
        return len(self._results)
