"""initial schema: system tables and modulo1

Revision ID: 9cd894b8e0bf
Revises: 
Create Date: 2026-09-07 22:38:14.780832+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd894b8e0bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('curr_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.String(), nullable=False),
    sa.Column('processado_em', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('_outbox_events', schema=None) as batch_op:
        batch_op.create_index('idx_outbox_status', ['status'], unique=False)

    op.create_table('_schema_migrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_table('mod_modulo1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dados_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='ativo', nullable=True),
    sa.Column('ativo', sa.Integer(), server_default='1', nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mod_modulo1', schema=None) as batch_op:
        batch_op.create_index('idx_modulo1_ativo', ['ativo'], unique=False)
        batch_op.create_index('idx_modulo1_deletado', ['deletado_em'], unique=False)
        batch_op.create_index('idx_modulo1_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mod_modulo1', schema=None) as batch_op:
        batch_op.drop_index('idx_modulo1_status')
        batch_op.drop_index('idx_modulo1_deletado')
        batch_op.drop_index('idx_modulo1_ativo')

    op.drop_table('mod_modulo1')
    op.drop_table('_schema_migrations')
    with op.batch_alter_table('_outbox_events', schema=None) as batch_op:
        batch_op.drop_index('idx_outbox_status')

    op.drop_table('_outbox_events')
    op.drop_table('_audit_log')
    # ### end Alembic commands ###
